server:
  servlet:
    session:
      timeout: 1800

spring:
  security:
    user:
      name: admin
      password: 1234
      roles: USER, ADMIN
#  datasource:
#    url: jdbc:mariadb://localhost:3306/
#    username: cocolabhub
#    password: cocolabhub
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace #JPA 파라미터 콘솔에서 확인가능

#마이바티스 mapper 위치
#log-impl은 쿼리문 출력
mybatis:
  mapper-locations: classpath:sqlmapper/mysql/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


